env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    
task:
    name: motoonepower
    container:
    image: aarunalr/aosp-build
    cpu: 8
    memory: 32g
    
    install_spript:
     - bash update
    test_script:
      - bash test
    upload_script:
      - bash uploadccache  
