env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    
task:
    name: motoonepower
    container:
      image: aarunalr/aosp-build
      cpu: 16
      memory: 32g
    
    update_spript:
     - bash update
    
    test_script:
      - bash test
