env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    
task:
    name: motoonepower
    container:
      image: aarunalr/aosp-build
    
    update_spript:
     - bash update
    
    test_script:
      - bash test
