env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    
task:
    name: motoonepower
    timeout_in: 4h
    persistent_worker:
    labels:
      name: AX61-1
    container:
      image: aarunalr/aosp-build
      cpu: 12
      memory: 32g
    
    setup_script:
      - bash setup
    dccache_script:
      - bash dccache
    sync_script:
      - bash sync
    build_script:
      - bash build
    upload_script:
      - bash uccache  
