env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    
task:
    name: motoonepower
    timeout_in: 4h
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32g
    
    setup_script:
      - bash setup
    sync_script:
      - bash sync
    build_script:
      - bash build
