env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    
task:
    name: motoonepower
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32g
      commands:
      - sudo apt-get install gpg
      - sudo apt-get update
      - sudo apt-get upgrade
     test_script: # To test rom
      - bash test # test build script
