env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    
task:
    name: motoonepower
    timeout_in: 4h
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32g
      commands:
      - apt-get update && apt-get upgrade -y
      - apt install gpg wget unzip aria2 -y
      - mkdir -p /tmp/rom
      - mkdir -p /tmp/ccache
    dccache_script:
      - bash dccache
    sync_script:
      - bash sync
    build_script:
      - bash build
    upload_script:
      - bash uccache  
