env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    
task:
    name: motoonepower
    container:
      image: aarunalr/aosp-build
    
    update:
    - apt-get update && apt-get upgrade -y
    - apt install gpg -y
    
    test_script:
      - bash test
