env:
    CIRRUS_CLONE_DEPTH: 1
    
task:
    name: motoonepower
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32g
      commands:
      - sudo apt-get install gpg
      - apt-get update
      - apt-get upgrade
      volumes:
          - /home/cirrus/roms:/home/cirrus/roms
          - /home/cirrus/ccache:/home/cirrus/ccache
      
     test_script: # To test rom
      - bash test # test build script
