env:
    CIRRUS_CLONE_DEPTH: 1
    
task:
    name: motoonepower
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32g
      
test_script: # To build rom
      - bash test # Rom build script
