#!/bin/bash
cd /tmp/rom

export ROM_LINK=https://github.com/PixelPlusUI-SnowCone/manifest
export ROM_BRANCH=ppui
export DEVICE_BRANCH=ppui
export DEVICE_LUNCH=aosp_chef-userdebug
export BUILD_FLAG0=mka
export BUILD_FLAG1=bacon
