#!/bin/bash

cd /tmp/rom

# git configs
git config --global user.email "rushiranpise17@gmail.com"
git config --global user.name "Rushi Ranpise"
git config --global color.ui true

# sync rom
repo init --depth=1 --no-repo-verify -u https://github.com/AospExtended/manifest -b 12.x -g default,-mips,-darwin,-notdefault
git clone https://github.com/rushiranpise/local_manifest.git --depth 1 -b aex .repo/local_manifests
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync --fail-fast -j8

rm -rf device/motorola/chef/GoogleCameraGo
